Document: flask-app
Title: Debian flask-app Manual
Author: <insert document author here>
Abstract: This manual describes what flask-app is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/flask-app/flask-app.sgml.gz

Format: postscript
Files: /usr/share/doc/flask-app/flask-app.ps.gz

Format: text
Files: /usr/share/doc/flask-app/flask-app.text.gz

Format: HTML
Index: /usr/share/doc/flask-app/html/index.html
Files: /usr/share/doc/flask-app/html/*.html
